# Build settings
markdown: kramdown
remote_theme: pages-themes/midnight
#theme: midnight

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Site Info
title: Homepage of Sophia Fox
description: The profile and linktree for Sophia Fox in Las Vegas, NV